### PR TITLE
chore: add pre-commit hook

### PR DESCRIPTION
**Pull request by leroyguillaume**
Add pre-commit hook.

Need a new git tag to be used.

### CODE REVIEW

**Comment by est31** [comment]
Thanks! This is a great way to use cargo-udeps. I think it makes sense maybe somewhere in a README section or something?

**Comment by leroyguillaume** [comment]
> Thanks! This is a great way to use cargo-udeps. I think it makes sense maybe somewhere in a README section or something?

Good point! I updated the README!

**Comment by est31** [comment]
I'd like to have *only* the readme changes. Adding the file to the repo doesn't seem useful to me.

**Comment by leroyguillaume** [comment]
> I'd like to have _only_ the readme changes. Adding the file to the repo doesn't seem useful to me.

The file `.pre-commit-hooks.yaml` is mandatory to use the pre-commit hook.

**Pull request merged**
