### PR TITLE
Switch from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by qryxip**
The biggest advantage of GitHub Actions is [this](https://help.github.com/en/articles/about-github-actions#usage-limits).

> - You can execute up to 20 workflows concurrently per repository.
> - You can execute up to 1000 API requests in an hour across all actions within a repository.
> - Each job in a workflow can run for up to 6 hours of execution time.
> - You can run up to 20 jobs concurrently per repository across all workflows.

Furthermore,
- We can use sophisticated scripts as components. (for example, [actions-rs](https://github.com/actions-rs))
- `$GITHUB_TOKEN` is automatically set.

### CODE REVIEW

**Comment by est31** [comment]
Can you remove the last commit? crates.io doesn't support per-crate publish keys yet.

**Comment by qryxip** [comment]
Ok. I removed the commit. And
- `s/target_triple/target/`
- Updated `README.md`.

**Comment by qryxip** [comment]
- `v[0-9]+.[0-9]+.[0-9]+*` → `v[0-9]+.[0-9]+.[0-9]+**`

**Comment by qryxip** [comment]
Running `jobs.release` on `qryxip/cargo-udeps` just in case.
<https://github.com/qryxip/cargo-udeps/runs/258284248>

**Comment by qryxip** [comment]
<https://github.com/qryxip/cargo-udeps/commit/241f221a76020bcea5b0868fd9f419215cbb2831/checks?check_suite_id=263132388>

**Comment by qryxip** [comment]
```diff
       - name: GH Release
-        uses: softprops/action-gh-release@v0.1.0
+        uses: softprops/action-gh-release@v0.1.3
```

**Pull request merged**
